name: Build Windows Binaray
on: push
jobs:
  Build-Windows-Binaray:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.3.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: 'true'
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make all -j


