name: Build Windows Binaray
on: push
jobs:
  Build-Windows-Binaray:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.3.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: 'true'
          tools: 'tools_ninja'
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir build
          cd build
          call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat" x86_amd64
          cmake -G Ninja ..
          ninja
        shell: cmd
      - name: Deploy
        run: |
          cd build
          mkdir output
          mv ImageLabel.exe output
          cd output
          windeployqt ImageLabel.exe
      - name: Archive
        run: Compress-Archive .\build\output\* -DestinationPath ./ImageLabel_win_x86_64.zip -CompressionLevel Optimal
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ImageLabel_win_x86_64.zip
          tag_name: ${{ github.run_number }}