name: Build Windows Binaray
on: push
jobs:
  Build-Windows-Binaray:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.3.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: 'true'
          tools: 'tools_ninja'
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir build
          ls
          cd build
          cmd.exe /c 'C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat'
          cmake -G Ninja -D CMAKE_CXX_COMPILER=cl.exe ..
          ls
          ninja
